---
- name: Ubuntu 24.04 Üzerine Zabbix Server 7.2 Kurulumu ve Yapılandırma
  hosts: zabbix
  become: yes
  vars:
    zabbix_db_user: "zabbix"
    zabbix_db_password: "password"
    zabbix_db_name: "zabbix"

  tasks:
    - name: Gerekli Bağımlılıkları yükleme
      apt:
        name: ["wget", "gnupg"]
        state: present
        update_cache: yes

    - name: PostgreSQL'i yükleme
      apt:
        name: postgresql
        state: present

    - name: Python ve PostgreSQL bağımlıklarını yükleme
      apt:
        name: python3-psycopg2
        state: present
        
    - name: Zabbix depo paketlerini indirme
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb"
        dest: "/tmp/zabbix-release_latest_7.2+ubuntu24.04_all.deb"

    - name: Zabbix deposunu kurma
      command: dpkg -i /tmp/zabbix-release_latest_7.2+ubuntu24.04_all.deb
      args:
        creates: /etc/apt/sources.list.d/zabbix.list

    - name: Paketleri güncelleme
      apt:
        update_cache: yes

    - name: Zabbix Server, Frontend ve Agent2 için gerekli paketleri yükleme
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.3-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent2
        state: present

    - name: Zabbix agent 2 pluginlerini yükleme
      apt:
        name:
          - zabbix-agent2-plugin-mongodb
          - zabbix-agent2-plugin-mssql
          - zabbix-agent2-plugin-postgresql
        state: present

    - name: PostgreSQL çalıştığını doğrulama
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Zabbix veritabanı kullanıcısı oluştur
      become_user: postgres
      postgresql_user:
        name: "{{ zabbix_db_user }}"
        password: "{{ zabbix_db_password }}"
        role_attr_flags: "LOGIN"

    - name: Zabbix veritabanı oluştur
      become_user: postgres
      postgresql_db:
        name: "{{ zabbix_db_name }}"
        owner: "{{ zabbix_db_user }}"

    - name: Zabbix kullancıısı için PostgreSQL izinlerini ayarlama
      command: chmod u+rx /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz

    - name: Zabbix başlangıç database şemasını içeriye aktarma
      become: yes
      become_user: zabbix
      shell: zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | psql zabbix

    - name: Zabbix server için database şifresi yapılandırma
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^#?DBPassword='
        line: "DBPassword={{ zabbix_db_password }}"

    - name: Servisleri yeniden başlat
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent2
        - nginx
        - php8.3-fpm
